assignment_Panorbit/Panorbit/Panorbit/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('dashboard.urls')),
]

assignment_Panorbit/Panorbit/dashboard/urls.py
from django.urls import path
from django.urls import path
from django.conf.urls import url


from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.signup, name='index'),
    url(r'^signup_form/', views.signup_form, name='signup_form'),
    url(r'^signup_test/', views.signup_test, name='signup_test'),
    url(r'^check_if_mail_exist/', views.check_if_mail_exist, name='check_if_mail_exist'),
    url(r'^send_otp_email/', views.send_otp_email, name='send_otp_email'),
    url(r'^send_otp_email_registered/', views.send_otp_email_registered, name='send_otp_email_registered'),
    url(r'^validate_otp/', views.validate_otp, name='validate_otp'),
    url(r'^login/', views.login_sample, name='login_sample'),
    url(r'^login_test/', views.login_test, name='login_test'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^test/', views.test, name='test'),
    url(r'^selected_name/', views.selected_name, name='selected_name'),
    url(r'^country_details/', views.country_details, name='country_details'),
    url(r'^autocompleteModel/', views.autocompleteModel, name='autocompleteModel'),
]

assignment_Panorbit/Panorbit/dashboard/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models


class CustomUser(AbstractBaseUser):
    email = models.CharField(primary_key=True, max_length=254)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_number = PhoneNumberField(null=False, blank=False, unique=True)
    REQUIRED_FIELDS = ['username', 'phone_number']
    USERNAME_FIELD = 'email'



    class Meta:
        managed = True
        db_table = 'dashboard_customuser'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return self.email

    def get_by_natural_key(self, username):
        return self.username


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_unusable_password()
        user.save(using=self._db)
        return user


class City(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=35)  # Field name made lowercase.
    countrycode = models.ForeignKey('Country', models.DO_NOTHING, db_column='CountryCode')  # Field name made lowercase.
    district = models.CharField(db_column='District', max_length=20)  # Field name made lowercase.
    population = models.IntegerField(db_column='Population')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'city'


class Country(models.Model):
    code = models.CharField(db_column='Code', primary_key=True, max_length=3)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=52)  # Field name made lowercase.
    continent = models.CharField(db_column='Continent', max_length=13)  # Field name made lowercase.
    region = models.CharField(db_column='Region', max_length=26)  # Field name made lowercase.
    surfacearea = models.FloatField(db_column='SurfaceArea')  # Field name made lowercase.
    indepyear = models.SmallIntegerField(db_column='IndepYear', blank=True, null=True)  # Field name made lowercase.
    population = models.IntegerField(db_column='Population')  # Field name made lowercase.
    lifeexpectancy = models.FloatField(db_column='LifeExpectancy', blank=True, null=True)  # Field name made lowercase.
    gnp = models.FloatField(db_column='GNP', blank=True, null=True)  # Field name made lowercase.
    gnpold = models.FloatField(db_column='GNPOld', blank=True, null=True)  # Field name made lowercase.
    localname = models.CharField(db_column='LocalName', max_length=45)  # Field name made lowercase.
    governmentform = models.CharField(db_column='GovernmentForm', max_length=45)  # Field name made lowercase.
    headofstate = models.CharField(db_column='HeadOfState', max_length=60, blank=True, null=True)  # Field name made lowercase.
    capital = models.IntegerField(db_column='Capital', blank=True, null=True)  # Field name made lowercase.
    code2 = models.CharField(db_column='Code2', max_length=2)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'country'


class Countrylanguage(models.Model):
    countrycode = models.ForeignKey(Country, models.DO_NOTHING, db_column='CountryCode', primary_key=True)  # Field name made lowercase.
    language = models.CharField(db_column='Language', max_length=30)  # Field name made lowercase.
    isofficial = models.CharField(db_column='IsOfficial', max_length=1)  # Field name made lowercase.
    percentage = models.FloatField(db_column='Percentage')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'countrylanguage'
        unique_together = (('countrycode', 'language'),)


class CheckOtp(models.Model):
    email = models.CharField(max_length=255)
    otp = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'check_otp'

assignment_Panorbit/Panorbit/dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text='Required. Add a valid email address')

    class Meta:
        model = CustomUser
        fields = ("email", "phone_number", "first_name", "last_name", "gender")

    def __int__(self):
        self.fields['password1'].required = False
        self.fields['password2'].required = False

assignment_Panorbit/Panorbit/dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,JsonResponse
from django.conf import settings
# Create your views here.
from django_otp.oath import hotp
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from .models import *
import json
from django.core import serializers
from django import forms
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import logout as django_logout
from django.core.mail import send_mail
from random import randint


# @login_required(login_url='/accounts/login/')
@csrf_exempt
def autocompleteModel(request):
    data = json.loads(request.body)
    print(data,"hdsgfgsdhfhdsg")
    results = []
    search_country = Country.objects.filter(name__istartswith=data['search']).using('world')
    search_city = City.objects.filter(name__istartswith=data['search']).using('world')
    search_language = Countrylanguage.objects.filter(language__istartswith=data['search']).using('world')
    print(search_country)
    for r in search_country:
        results.append(r.name)
    for r in search_city:
        results.append(r.name)
    for r in search_language:
        results.append(r.language)
    print(results)
    # resp = request.REQUEST['callback'] + '(' + json.dumps(results) + ');'
    return JsonResponse(results, safe=False)

@csrf_exempt
def login_sample(request):
    print("in login form")
    return render(request, 'dashboard/login.html')

@login_required(login_url='login/')
@csrf_exempt
def selected_name(request):
    input = request.GET['name']
    options = request.GET['options']
    print(options)
    results_country = []
    results = []
    if options == "0":
        print("in if")
        search_country = Country.objects.filter(name=input).using('world')
        search_city = City.objects.filter(name=input).using('world')
        search_language = Countrylanguage.objects.filter(language=input).using('world')
    else:
        print("in else")
        search_country = Country.objects.filter(name__istartswith=input).using('world')
        search_city = City.objects.filter(name__istartswith=input).using('world')
        search_language = Countrylanguage.objects.filter(language__istartswith=input).using('world')
    for r in search_country:
        results_country.append(r.name)
    for r in search_city:
        results.append(r.name)
    for r in search_language:
        results.append(r.language)
    print(results)
    return render(request, "dashboard/results.html", {"results": results, "results_country": results_country})


@login_required(login_url='/home/login/')
@csrf_exempt
def country_details(request):

    input = request.GET['name']
    country_details = Country.objects.using('world').get(name=input)
    print(country_details)
    return render(request, "dashboard/country_details.html", {"country_details": country_details})


# @login_required(login_url='/home/login/')
def signup(request):
    for counter in range(5):
        print(hotp(key=settings.OTP_SECRET_KEY, counter=counter, digits=6))
    return render(request, "dashboard/index.html")


@login_required(login_url='/home/login/')
@csrf_exempt
def dashboard(request):
    return render(request, "dashboard/dashboard.html")


@csrf_exempt
def signup_form(request):
    if request.method == "POST":
        data = json.loads(request.body)
        CustomUser(first_name=data['first_name'], last_name=data['last_name'], email=data['email'], phone_number=data['phone_number']).save()
        print(hotp(key=settings.OTP_SECRET_KEY, counter=1, digits=7))

    return HttpResponse(request.body)


@csrf_exempt
def signup_test(request):
    context = {}
    if request.POST:
        print("in post")
        print(request.POST)
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
        else:
            context['registration_form'] = form
            print(form.errors)
    else:  # GET request
        form = RegistrationForm()
        context['registration_form'] = form
    print(context)
    return render(request, "dashboard/index.html", context)


@csrf_exempt
def login_test(request):
    context = {}
    if request.POST:
        print("in post")
        print(request.POST)
        email = request.POST['email']
        user = CustomUser.objects.get(email=email)
        login(request, user)
        return redirect('dashboard')
    else:  # GET request
        form = RegistrationForm()
        context['registration_form'] = form
    print(context)
    return render(request, "dashboard/index.html", context)

@csrf_exempt
def send_otp_email(request):
    print("in send otp")
    email = json.loads(request.body)['email']
    print(email)
    n = 6
    range_start = 10 ** (n - 1)
    range_end = (10 ** n) - 1
    otp = randint(range_start, range_end)
    # try:
    count = CheckOtp.objects.filter(email=email).count()
    print(count)
    if count == 0:
        CheckOtp(email=email, otp=otp).save()

    else:
        CheckOtp.objects.filter(email=email).update(otp=otp)
    # except:
    #     CheckOtp(email=email, otp=otp).save()
    send_mail('OTP', 'Here is the message.'+str(otp), settings.EMAIL_HOST_USER,
              [email], fail_silently=False)
    return HttpResponse("success")


@csrf_exempt
def send_otp_email_registered(request):
    email = json.loads(request.body)['email']
    print(email)
    n = 6
    range_start = 10 ** (n - 1)
    range_end = (10 ** n) - 1
    otp = randint(range_start, range_end)
    print(otp)
    # try:
    count = CheckOtp.objects.filter(email=email).count()
    print(count)
    if count == 1:
        CheckOtp.objects.filter(email=email).update(otp=otp)
        send_mail('OTP', 'Here is the message.' + str(otp), settings.EMAIL_HOST_USER,
                  [email], fail_silently=False)
    else:
        return HttpResponse("no")
    return HttpResponse("success")


@csrf_exempt
def validate_otp(request):
    email = json.loads(request.body)['email']
    otp = json.loads(request.body)['otp']
    count = CheckOtp.objects.filter(email=email,otp=otp).count()
    if count == 0:
        return HttpResponse("invalid")
    else:
        return HttpResponse("valid")




@csrf_exempt
def logout(request):
    django_logout(request)
    return redirect('index')

@csrf_exempt
def test(request):
    return render(request, 'dashboard/logout.html')

@csrf_exempt
def check_if_mail_exist(request):
    mail = json.loads(request.body)['email']
    print(mail,"mail")
    count = CustomUser.objects.filter(email=mail).count()
    print(count)
    return HttpResponse(count)

assignment_Panorbit/Panorbit/dashboard/templates/dashboard/country_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Country details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <form method="post" action="/home/logout/" style="display: flex;
    margin-right: 15px;
    margin-top: 10px;
    justify-content: flex-end;">
             <button type="submit" class="btn btn-primary" style="background-color: #2196F3;
    border-color: #2196F3;">Logout</button>
 </form>
    <h3 style="text-align: center;">Country Details</h3>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div><b>Country Code: </b><p1>{{ country_details.code }}</p1></div>
                <div><b>Country Name: </b><p1>{{ country_details.name }}</p1></div>
                <div><b>Continent: </b><p1>{{ country_details.continent }}</p1></div>
                <div><b>Region: </b><p1>{{ country_details.region }}</p1></div>
                <div><b>Surface Area: </b><p1>{{ country_details.surfacearea }}</p1></div>
                <div><b>Indeep Year: </b><p1>{{ country_details.indeepyear }}</p1></div>
                <div><b>Population: </b><p1>{{ country_details.population }}</p1></div>
                <div><b>Life Expectance: </b><p1>{{ country_details.lifeexpectancy }}</p1></div>
                <div><b>City Details: </b>
                    <!--{{ country_details.city_set.select_related.all }}-->
                    {% for part in country_details.city_set.select_related.all %}
                    <p style="margin-bottom:1px;"><b>name:  </b>{{ part.name }}    <b>district:  </b>{{ part.district }}              <b>population:  </b>{{ part.population }}</p>
                    {% endfor %}
                </div>


            </div>
            <div class="col-md-6">
                <div><b>GNP: </b><p1>{{ country_details.gnp }}</p1></div>
                <div><b>GNPOld: </b><p1>{{ country_details.gnpold }}</p1></div>
                <div><b>Local Name: </b><p1>{{ country_details.localname }}</p1></div>
                <div><b>Government Form:</b><p1>{{ country_details.governmentform }}</p1></div>
                <div><b>HeadOfState: </b><p1>{{ country_details.headofstate }}</p1></div>
                <div><b>Capital: </b><p1>{{ country_details.capital }}</p1></div>
                <div><b>Code2: </b><p1>{{ country_details.code2 }}</p1></div>
                <div><b>Languages: </b>
                    {% for part in country_details.countrylanguage_set.select_related.all %}
                       <p1>{{ part.language }}, </p1>
                    {% endfor %}
                </div>



            </div>
        </div>
        <!--<div class="row">-->
            <!--<table class="table">-->
                <!--<thead>-->
                    <!--<tr>-->
                        <!--<th>Name</th>-->
                        <!--<th>District</th>-->
                        <!--<th>Population</th>-->
                    <!--</tr>-->
                <!--</thead>-->
                <!--<tbody>-->
                    <!--{% for part in country_details.city_set.select_related.all %}-->
                        <!--<tr>-->
                            <!--<td>{{ part.name }}</td>-->
                            <!--<td>{{ part.district }}</td>-->
                            <!--<td>{{ part.population }}</td>-->
                        <!--</tr>-->
                    <!--{% endfor %}-->
                <!--</tbody>-->
            <!--</table>-->
            <!--<div>Languages</div>-->
            <!--{% for part in country_details.countrylanguage_set.select_related.all %}-->
               <!--<p1>{{ part.language }}</p1>-->
            <!--{% endfor %}-->
        <!--</div>-->
    </div>



</body>
</html>

assignment_Panorbit/Panorbit/dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.5/xlsx.full.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.5/jszip.js"></script>
<style>
* {
  box-sizing: border-box;
}

body {
  font: 16px Arial;
}

/*the container must be positioned relative:*/
.autocomplete {
  position: relative;
  display: inline-block;
}

input {
  border: 1px solid transparent;
  background-color: #f1f1f1;
  padding: 10px;
  font-size: 16px;
}

input[type=text] {
  background-color: #f1f1f1;
  width: 100%;
}

input[type=submit] {
  background-color: DodgerBlue;
  color: #fff;
  cursor: pointer;
}

.autocomplete-items {
  position: absolute;
  border: 1px solid #d4d4d4;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  /*position the autocomplete items to be the same width as the container:*/
  top: 100%;
  left: 0;
  right: 0;
}

.autocomplete-items div {
  padding: 10px;
  cursor: pointer;
  background-color: #fff;
  border-bottom: 1px solid #d4d4d4;
}

/*when hovering an item:*/
.autocomplete-items div:hover {
  background-color: #e9e9e9;
}

/*when navigating through the items using the arrow keys:*/
.autocomplete-active {
  background-color: DodgerBlue !important;
  color: #ffffff;
}
</style>
<script type="text/javascript">

    function submitdata(){
        var input = $('#myInput').val();
        var selected = $("#myInputautocomplete-list").length;
        window.open("/home/selected_name/?name="+input+"&options="+selected);
    }


    function searchOpen() {
    console.log("search open")
    var search = $('#myInput').val();
    $.ajax({
        type: 'post',
        url: '/home/autocompleteModel/',
        data: JSON.stringify({'search':search}) ,
        dataType: 'json',
        success: function(response) {
        var i = 0;
        console.log(response.length)
        console.log(response[0])
        $('input[name=search]').after('<div id="myInputautocomplete-list" class="autocomplete-items"><div>');
        while(i<response.length){
            console.log(response[i])
            $('#myInputautocomplete-list').append('<div onclick="clicked(this);" id="'+response[i]+'">'+response[i]);
            i = i+1;
         }

        },
        error: function(response) {
            alert("fail")
        },
    });
    }

    function clicked(item) {
        $("#myInput").val($(item).attr("id"));
    }


</script>
</head>
<body>
 {% block content %}
<!--Make sure the form has the autocomplete function switched off:-->
 <form method="post" action="/home/logout/" style="display: flex;
    margin-right: 15px;
    margin-top: 10px;
    justify-content: flex-end;">
             <button type="submit" class="btn btn-primary" style="background-color: #2196F3;
    border-color: #2196F3;">Logout</button>
 </form>
<div autocomplete="off" style="display: flex;justify-content: center;">
  <div class="autocomplete" style="width:300px;">
    <input id="myInput" type="text" name="myCountry" placeholder="Search City/Country/Language" onkeyup="searchOpen()">
  </div>
    <button type="submit" onclick="submitdata()" style="width: 6%;
    background: #2196F3;
    border-color: #2196F3;
    border: 0px;"><i class="fa fa-search" style="color:aliceblue;"></i></button>
  <input type="submit" onclick="submitdata()" style="display:none;">
</div>
{% endblock %}
<script>
function autocomplete(inp, arr) {
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      this.parentNode.appendChild(a);
      for (i = 0; i < arr.length; i++) {
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/
var countries = []
/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("myInput"), countries);
</script>

</body>
</html>

assignment_Panorbit/Panorbit/dashboard/templates/dashboard/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.5/xlsx.full.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.5/jszip.js"></script>
</head>
<body>
    <div class="contailner">
        <form method="post" action="/home/logout/" style="display: flex;
    margin-right: 15px;
    margin-top: 10px;
    justify-content: flex-end;">
             <button type="submit" class="btn btn-primary">Logout</button>
        </form>
    </div>
</body>
</html>

assignment_Panorbit/Panorbit/dashboard/templates/dashboard/results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Details</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script>
      function country_details(item) {
        input = $(item).attr("id");
        location.replace("/home/country_details/?name="+input);
    }
  </script>
</head>
<body>

<form method="post" action="/home/logout/" style="display: flex;
    margin-right: 15px;
    margin-top: 10px;
    justify-content: flex-end;">
             <button type="submit" class="btn btn-primary" style="background-color: #2196F3;
    border-color: #2196F3;">Logout</button>
 </form>

<div class="container">
  <table class="table" style="
    border: 3px solid aliceblue;">
    <thead>
      <tr>
        <th>Search</th>
      </tr>
    </thead>
    <tbody>
        {% for post in results_country %}
            <tr class="country" id = "{{ post }}" onclick="country_details(this);" style="cursor:pointer;" ><td>{{ post }}</td></tr>
        {% endfor %}
        {% for post in results %}
            <tr><td>{{ post }}</td></tr>
        {% endfor %}
    </tbody>
  </table>
</div>

</body>
</html>